config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "start#index"
  resources :users
  resources :posts
  # resources :comments
  resources :posts do
    resources :comments
  end
  get '/users/:id/subscribe' => 'users#subscribe', as: 'subscribe_user'
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe_user'
  resources :tags, only:[:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :post
    belongs_to :user
    validates :body, presence: true, length:{ minimum: 5}

end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, :dependent => :destroy
    belongs_to :user
    has_many :taggings
    has_many :tags, through: :taggings
    validates :title, presence:true,
                        length: { minimum: 5 }

    def all_tags
        self.tags.map(&:name).join(', ')
    end

    def all_tags=(names)
        self.tags = names.split(',').map do |name|
            Tag.where(name: name.strip).first_or_create!
        end
    end
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord

  belongs_to :user
  belongs_to :subscribable, class_name: "User"

end

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :taggings
    has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :subscribes, dependent: :destroy
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable ,:confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
         end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params.merge(post_id: @post.id, user_id: current_user.id))
        redirect_to post_path(@post)
    end
    
    def destroy
            @post = Post.find(params[:post_id])
            @comment = @post.comments.find(params[:id])
            @comment.destroy
            redirect_to post_path(@post)
    end

    private 
        def comment_params
            params.require(:comment).permit(:body, :post_id, :user_id)
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user!, exept: [:index, :show]


    def index
        @posts = Post.all
    end
     
    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post= Post.find(params[:id])                    #редактирование аккаунтов       
        if @post.update(posts_params)            # если аккаунт редактируется переводит на страницу отредактированного акканта 
            redirect_to @post# если аккаунт редактируется переводит на страницу отредактированного акканта 
        else
            render 'edit'                                 #если нет по возвращает на страницу редактирования аккаунтов
        end

    end

    def create 
        @post = Post.new(posts_params.merge(user_id: current_user.id))         #создание post
        if @post.save                              # если аккаунт создаётся переводит на страницу нового акканта 
            redirect_to @post                   # если аккаунт создаётся переводит на страницу нового акканта 
        else                                      # если нет то возвращает на страницу создания аккаунтов
            render 'new'# если нет то возвращает на страницу создания аккаунтов
        end
    end

    def destroy
        @post = Post.find(params[:id])  #выбирает по айди
        @post.destroy        #Удаляет строку из таблицы 
        redirect_to posts_path    # возвращает на страницу аккаунтов
    end

    private 

    def posts_params
        params.require(:post).permit(:title, :text, :user_id, :all_tags)
    end


end

app/controllers/start_controller.rb
class StartController < ApplicationController

    def index
        
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def show
        @tag = Tag.find_by(name: params[:id])
        @posts = @tag.posts
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :subscribe, :unsubscribe]
    before_action :authenticate_user!, exept: [:index, :show]
    
    def index
        @users = User.all
    end

    def show
    end
  
    def subscribe 
      if current_user.id == @user.id
        redirect_to user_path(@user), notice: 'Вы не можете подписаться сами на себя.'
      else
        if current_user.subscribes.exists?(subscribable_id: @user.id)
          redirect_to user_path(@user), notice: 'Вы уже подписаны на данного пользователя.'
        else
          @subscribe = current_user.subscribes.build
          @subscribe.subscribable_id = @user.id
          if @subscribe.save
              redirect_to user_path(@user), notice: 'Вы подписались на этого пользователя.'
          end
        end
      end
    end

    def unsubscribe
      if current_user.id == @user.id
        redirect_to user_path(@user), notice: 'Вы не можете подписаться сами на себя.'
      else
        if current_user.subscribes.exists?(subscribable_id: @user.id)
          @subscribe = current_user.subscribes.find_by_subscribable_id(@user.id)
          @subscribe.destroy
          redirect_to user_path(@user), notice: 'Вы отписались от него'
        else
          redirect_to user_path(@user), notice: 'Вы не были подписаны на данного пользователя.'
        end
      end
    end

    private

    def set_user
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb

<div class = "post">
  <div class = "post-head">
    <h6 class = "text-md-start" >Коментатор: <%= comment.user.name %>
      <% if current_user.id == comment.user.id%>
        <%= link_to 'Удалить коментарий', [comment.post, comment], class: "btn btn-primary btn-sm",
                                          method: :delete,
                                          data: { turbo_method: :delete,confirm: 'Ты точно этого хочешь?' } %>
      <%end%>
    </h6>
    <small class ="post-text p-4"><%= comment.body %></small>
  </div>
</div>

app/views/comments/_form.html.erb

<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
  
  <div class="form-group">
    <%= form.label :Текст_коментария %><br>
    <%= form.text_area :body, class: 'form-control' %>
  </div>
  <p>
    <%= form.submit "Написать", class: "btn btn-primary" %>
  </p>

<% end %>




app/views/comments/show.html.erb

<p>
  <strong>Заголовок:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Сообщение:</strong>
  <%= @post.text %>
</p>
 
<h2>Коментарии</h2>
<%= render @post.comments %>
 
<h2>Добавить коментарий:</h2>
<%= render 'comments/form' %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aboba</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
    <div class="container">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
          <span class="fs-4">ABOBA jobs</span>
        </a>

        <ul class="nav nav-pills ">
          <li class="nav-item "><span class="nav-link " aria-current="page"><%= link_to "Пользователи", users_path%></span></li>
          <li class="nav-item"><span class="nav-link " aria-current="page"><%= link_to "Посты", posts_path%></span></li>
          <li class="nav-item"><a href="#" class="nav-link">new</a></li>
          <% if user_signed_in?%>
            <li class="nav-item" ><span class="nav-link ">Привет <%= current_user.name %></span></li>
            <li class="nav-item"><span class="nav-link " aria-current="page"><%= link_to "Выход", destroy_user_session_path, data:{ "turbo-method": :delete}%></span></li>
          <% else %>
            <li class="nav-item"><span class="nav-link " aria-current="page"><%= link_to "Вход", new_user_session_path%></span></li>
            <li class="nav-item"><span class="nav-link " aria-current="page"><%= link_to "Регистрация", new_user_registration_path%></span></li>
          <% end %>
        </ul>
      </header>
    </div>
    
    <div class= "container main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb

<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :Заголовок %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :Сообщение %>
    <%= f.text_area :text, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :Тэги %>
    <%= f.text_area :all_tags, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Сохранить', class: "btn btn-primary" %>
    <%= link_to 'Назад', posts_path, class: "btn btn-outline-primary"%>
  </div>

<% end %>

app/views/posts/_post.html.erb
<article class = "post background-posts">
  <section class = "post-head">
    <h2> <%=link_to post.title, post_path(post) %></h2>
    <h6> <%=link_to post.user.name , user_path(post) %></h6>
    <div>Коментариев:<%= post.comments.length %></div>>
    <small>
      <time> <%= post.created_at.to_date.strftime("%d, %B, %Y") %></time> |
      <%if current_user.id == post.user.id%>
        <%= link_to 'Изменить', edit_post_path(post) %> |
        <%= link_to 'Удалить', post_path(post), data: {turbo_method: :delete, turbo_confirm: 'Ты точно этого хочешь?' } %>
      <% end %>
    </small>
  </section>

  <section class = "post-text">
    <%= post.text %>
  </section>

  <section class = "post-footer">
    <%= raw post.tags.map(&:name).map{|t| link_to t, tag_path(t), class: "badge bg-primary text-wrap" }.join(' ') %>
  </section>
</article>












app/views/posts/edit.html.erb
<h1>Редактирование статьи</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Посты</h1>
  <%= link_to "Новый пост", new_post_path, class: "btn btn-outline-primary "%>
<%= render @posts%>

app/views/posts/new.html.erb
<h1>Новый пост</h1>

<%=render 'form'%>

app/views/posts/show.html.erb
<article class = "post">
  <section class = "post-head">
    <h1> <%=@post.title %></h1>
    <h6> <%=link_to @post.user.name , user_path(@post) %></h6>
    <div>Коментариев:<%= @post.comments.length %></div>>
    <small>
      <time> <%= @post.created_at.to_date.strftime("%d, %B, %Y") %></time> |
      <%if current_user.id == @post.user.id%>
        <%= link_to 'Изменить', edit_post_path(@post) %> |
        <%= link_to 'Удалить', post_path(@post), data: {turbo_method: :delete, turbo_confirm: 'Ты точно этого хочешь?' } %>
      <% end %>
    </small>
  </section>

  <section class = "post-text">
    <%= @post.text %>
  </section>
</article>









<%= render @post.comments %>
 
<hr>


<%= render 'comments/form' %>

<%= link_to 'Назад', posts_path %>




app/views/start/index.html.erb
<div class = "start" >Hello Gays!! </div>

app/views/tags/show.html.erb
<h1> <%= @tag.name %></h1>

<%if @tag.posts.empty? %>
  <h2> Постов нету </h2>
<% else %>
  <%= render @tag.posts %>

<% end %>

app/views/users/index.html.erb
<h1>Пользователи</h1>
 

<table class="table table-success table-striped">
  <tr>
    <th class="col">Имя</th>
    <th class="col">Email</th>
    <th class="col">Постов</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
        <td><%=link_to "#{user.name}", user_path(user)%></td>
        <td><%= user.email %></td>
        <td><%=user.posts.length %></td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>




<% if current_user.id == @user.id%>
<% else %>
  <% if current_user.subscribes.exists?(subscribable_id: @user.id)%>
    <%= link_to "Отписаться", unsubscribe_user_path(@user) %>|
  <% else %>
    <%= link_to "Подписаться", subscribe_user_path(@user) %>|
  <% end %>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>